spring:
  datasource:
    # Heroku DB
    url: jdbc:postgresql://ec2-176-34-211-0.eu-west-1.compute.amazonaws.com:5432/dc95stcbfjr73h
    username: toazurekmbehjx
    password: 81ae43343533c7960ab00d1c080d9400371360eba6d91b0c756ec9d1c2cb64ac

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 9002

